/*
Commie Plugin API

API for communication between Commie and plugins via CPCP (Commie Plugin Connectivity Protocol).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RunCommandRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunCommandRequest{}

// RunCommandRequest struct for RunCommandRequest
type RunCommandRequest struct {
	// Command name
	Command string `json:"command"`
}

type _RunCommandRequest RunCommandRequest

// NewRunCommandRequest instantiates a new RunCommandRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunCommandRequest(command string) *RunCommandRequest {
	this := RunCommandRequest{}
	this.Command = command
	return &this
}

// NewRunCommandRequestWithDefaults instantiates a new RunCommandRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunCommandRequestWithDefaults() *RunCommandRequest {
	this := RunCommandRequest{}
	return &this
}

// GetCommand returns the Command field value
func (o *RunCommandRequest) GetCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *RunCommandRequest) GetCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *RunCommandRequest) SetCommand(v string) {
	o.Command = v
}

func (o RunCommandRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunCommandRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["command"] = o.Command
	return toSerialize, nil
}

func (o *RunCommandRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunCommandRequest := _RunCommandRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunCommandRequest)

	if err != nil {
		return err
	}

	*o = RunCommandRequest(varRunCommandRequest)

	return err
}

type NullableRunCommandRequest struct {
	value *RunCommandRequest
	isSet bool
}

func (v NullableRunCommandRequest) Get() *RunCommandRequest {
	return v.value
}

func (v *NullableRunCommandRequest) Set(val *RunCommandRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRunCommandRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRunCommandRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunCommandRequest(val *RunCommandRequest) *NullableRunCommandRequest {
	return &NullableRunCommandRequest{value: val, isSet: true}
}

func (v NullableRunCommandRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunCommandRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


