version: 3

tasks:
  commit:
    cmds:
      - commie -c commit
  implement:
    cmds:
      - commie -c implement
  dev:
    aliases:
      - d
    cmds:
      - go run .
  install:
    aliases:
      - i
    cmds:
      - rm -rfv dist
      - goreleaser --snapshot
      - cp dist/commie_linux_amd64_v1/commie ~/bin
  playground:
    desc: "Run the internal command playground"
    cmds:
      - echo "Launching Colorlog Playground..."
      - go run internal/cmd/colorlog-playground/main.go
