version: 3

tasks:
  dev:
    cmds:
      - go run .
  dev-install:
    cmds:
      - rm -rfv dist
      - goreleaser --snapshot
      - cp dist/commie_linux_amd64_v1/commie ~/bin
  playground:
    desc: "Run the internal command playground"
    cmds:
      - echo "Launching Colorlog Playground..."
      - go run internal/cmd/colorlog-playground/main.go
