version: 3

tasks:
  commit:
    cmds:
      - commie -c commit
  implement:
    cmds:
      - commie -c implement
  dev:
    aliases:
      - d
    cmds:
      - go run .
  install:
    aliases:
      - i
    cmds:
      - rm -rfv dist
      - goreleaser --snapshot
      - cp dist/commie_linux_amd64_v1/commie ~/bin
  playground:
    desc: "Run the internal command playground"
    cmds:
      - echo "Launching Colorlog Playground..."
      - go run internal/cmd/colorlog-playground/main.go
  generate-models:
    desc: "Generate Go models from OpenAPI schema"
    cmds:
      - |
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v $(pwd):/local \
          openapitools/openapi-generator-cli generate \
          -i /local/pkg/cpcp/schemas/cpcp-api.yaml \
          --config /local/pkg/cpcp/schemas/config.json \
          -g go \
          -o /local/pkg/cpcp/models
  generate-ts-models:
    desc: "Generate TypeScript models from OpenAPI schema"
    cmds:
      - |
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v $(pwd):/local \
          openapitools/openapi-generator-cli generate \
          -i /local/pkg/cpcp/schemas/cpcp-api.yaml \
          -g typescript-fetch \
          --config /local/pkg/cpcp/schemas/ts-config.json \
          -o /local/tsmodels