/* tslint:disable */
/* eslint-disable */
/**
 * Commie Plugin API
 * API for communication between Commie and plugins via CPCP (Commie Plugin Connectivity Protocol).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunCommandRequest
 */
export interface RunCommandRequest {
    /**
     * Command name
     * @type {string}
     * @memberof RunCommandRequest
     */
    command: string;
}

/**
 * Check if a given object implements the RunCommandRequest interface.
 */
export function instanceOfRunCommandRequest(value: object): value is RunCommandRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function RunCommandRequestFromJSON(json: any): RunCommandRequest {
    return RunCommandRequestFromJSONTyped(json, false);
}

export function RunCommandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunCommandRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
    };
}

export function RunCommandRequestToJSON(json: any): RunCommandRequest {
    return RunCommandRequestToJSONTyped(json, false);
}

export function RunCommandRequestToJSONTyped(value?: RunCommandRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
    };
}

