/* tslint:disable */
/* eslint-disable */
/**
 * Commie Plugin API
 * API for communication between Commie and plugins via CPCP (Commie Plugin Connectivity Protocol).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunCommand200Response
 */
export interface RunCommand200Response {
    /**
     * System prompt generated by the command
     * @type {string}
     * @memberof RunCommand200Response
     */
    prompt: string;
}

/**
 * Check if a given object implements the RunCommand200Response interface.
 */
export function instanceOfRunCommand200Response(value: object): value is RunCommand200Response {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function RunCommand200ResponseFromJSON(json: any): RunCommand200Response {
    return RunCommand200ResponseFromJSONTyped(json, false);
}

export function RunCommand200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunCommand200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
    };
}

export function RunCommand200ResponseToJSON(json: any): RunCommand200Response {
    return RunCommand200ResponseToJSONTyped(json, false);
}

export function RunCommand200ResponseToJSONTyped(value?: RunCommand200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
    };
}

