/* tslint:disable */
/* eslint-disable */
/**
 * Commie Plugin API
 * API for communication between Commie and plugins via CPCP (Commie Plugin Connectivity Protocol).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolOutput } from './ToolOutput';
import {
    ToolOutputFromJSON,
    ToolOutputFromJSONTyped,
    ToolOutputToJSON,
    ToolOutputToJSONTyped,
} from './ToolOutput';

/**
 * 
 * @export
 * @interface RunTools200Response
 */
export interface RunTools200Response {
    /**
     * 
     * @type {Array<ToolOutput>}
     * @memberof RunTools200Response
     */
    toolOutputs: Array<ToolOutput>;
}

/**
 * Check if a given object implements the RunTools200Response interface.
 */
export function instanceOfRunTools200Response(value: object): value is RunTools200Response {
    if (!('toolOutputs' in value) || value['toolOutputs'] === undefined) return false;
    return true;
}

export function RunTools200ResponseFromJSON(json: any): RunTools200Response {
    return RunTools200ResponseFromJSONTyped(json, false);
}

export function RunTools200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunTools200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'toolOutputs': ((json['tool_outputs'] as Array<any>).map(ToolOutputFromJSON)),
    };
}

export function RunTools200ResponseToJSON(json: any): RunTools200Response {
    return RunTools200ResponseToJSONTyped(json, false);
}

export function RunTools200ResponseToJSONTyped(value?: RunTools200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tool_outputs': ((value['toolOutputs'] as Array<any>).map(ToolOutputToJSON)),
    };
}

