/* tslint:disable */
/* eslint-disable */
/**
 * Commie Plugin API
 * API for communication between Commie and plugins via CPCP (Commie Plugin Connectivity Protocol).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolOutput
 */
export interface ToolOutput {
    /**
     * Name of the executed tool
     * @type {string}
     * @memberof ToolOutput
     */
    toolName: string;
    /**
     * Tool execution results
     * @type {{ [key: string]: any; }}
     * @memberof ToolOutput
     */
    result: { [key: string]: any; };
}

/**
 * Check if a given object implements the ToolOutput interface.
 */
export function instanceOfToolOutput(value: object): value is ToolOutput {
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ToolOutputFromJSON(json: any): ToolOutput {
    return ToolOutputFromJSONTyped(json, false);
}

export function ToolOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'toolName': json['tool_name'],
        'result': json['result'],
    };
}

export function ToolOutputToJSON(json: any): ToolOutput {
    return ToolOutputToJSONTyped(json, false);
}

export function ToolOutputToJSONTyped(value?: ToolOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tool_name': value['toolName'],
        'result': value['result'],
    };
}

