/* tslint:disable */
/* eslint-disable */
/**
 * Commie Plugin API
 * API for communication between Commie and plugins via CPCP (Commie Plugin Connectivity Protocol).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolManifest
 */
export interface ToolManifest {
    /**
     * Tool name
     * @type {string}
     * @memberof ToolManifest
     */
    name: string;
    /**
     * Tool description
     * @type {string}
     * @memberof ToolManifest
     */
    description: string;
    /**
     * Description of input parameters (similar to OpenAI API)
     * @type {{ [key: string]: any; }}
     * @memberof ToolManifest
     */
    parameters: { [key: string]: any; };
}

/**
 * Check if a given object implements the ToolManifest interface.
 */
export function instanceOfToolManifest(value: object): value is ToolManifest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    return true;
}

export function ToolManifestFromJSON(json: any): ToolManifest {
    return ToolManifestFromJSONTyped(json, false);
}

export function ToolManifestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolManifest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'parameters': json['parameters'],
    };
}

export function ToolManifestToJSON(json: any): ToolManifest {
    return ToolManifestToJSONTyped(json, false);
}

export function ToolManifestToJSONTyped(value?: ToolManifest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'parameters': value['parameters'],
    };
}

