/* tslint:disable */
/* eslint-disable */
/**
 * Commie Plugin API
 * API for communication between Commie and plugins via CPCP (Commie Plugin Connectivity Protocol).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolCall
 */
export interface ToolCall {
    /**
     * Name of the tool to invoke
     * @type {string}
     * @memberof ToolCall
     */
    toolName: string;
    /**
     * Input parameters for the tool
     * @type {{ [key: string]: any; }}
     * @memberof ToolCall
     */
    parameters: { [key: string]: any; };
}

/**
 * Check if a given object implements the ToolCall interface.
 */
export function instanceOfToolCall(value: object): value is ToolCall {
    if (!('toolName' in value) || value['toolName'] === undefined) return false;
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    return true;
}

export function ToolCallFromJSON(json: any): ToolCall {
    return ToolCallFromJSONTyped(json, false);
}

export function ToolCallFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolCall {
    if (json == null) {
        return json;
    }
    return {
        
        'toolName': json['tool_name'],
        'parameters': json['parameters'],
    };
}

export function ToolCallToJSON(json: any): ToolCall {
    return ToolCallToJSONTyped(json, false);
}

export function ToolCallToJSONTyped(value?: ToolCall | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tool_name': value['toolName'],
        'parameters': value['parameters'],
    };
}

